# Generated by Django 2.2 on 2021-03-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20200819_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipe',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('In Progress', 'в процессе'), ('Done', 'выполнено')], default='new', max_length=15, verbose_name='Модерация'),
        ),
        migrations.AlterField(
            model_name='tipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='webapp.Tag', verbose_name='Теги'),
        ),
    ]
