# Generated by Django 2.2 on 2021-03-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20210324_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
